---
title: "ZM Phyto Models"
output: html_document
date: "2024-02-02"
---

```{r package Setup, warning = F}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(mnsentinellakes)
library(mgcv)
library(gratia)
library(readxl)
library(cowplot)

select <- dplyr::select

early.anomaly = -17.52
late.anomaly = 14
```

# Read in semi cleaned data
````{r load in}
phytodata.cleanish <- read.csv("./data/ramsey_county_phytoplankton.csv") %>% 
  mutate(across(c(ALL.CELLS:CHRYSOS), ~ round(.x)))



ice_off <- read.csv("./data/ice_off_summarized.csv") %>%
  mutate(DNRID = fixlakeid(DOW)) %>% 
  dplyr::select(DNRID, year, min_ice_off_julian, min_ice_off_date) %>%
  dplyr::filter(DNRID == "82016700")

mean_ice <- ice_off  %>%
  dplyr::filter(year < 1980) %>%
  summarise(mean_ice_off = mean(min_ice_off_julian))

# Negative values indicate earlier anomalies
wb.ice = ice_off %>%
  add_row(data.frame(year = 2024, min_ice_off_julian = 67, min_ice_off_date = "2024-03-08")) %>%
  mutate(ice_off_anomaly = min_ice_off_julian - mean_ice$mean_ice_off) %>% 
  select(!DNRID) %>% 
  filter(year > 1980)
```


```{r cleaning}
temp <- merge( phytodata.cleanish, wb.ice, by = c("year")) %>% 
  mutate(days_since_ice = JULIANDAY - min_ice_off_julian) %>%
  mutate(ice_off_anomaly = as.numeric(ice_off_anomaly),
         JULIANDAY = as.numeric(JULIANDAY),
         year = as.numeric(year),
         year_f = as.factor(year),
         DNRID = as.factor(DNRID), 
         ice_off_anomaly_abs = abs(ice_off_anomaly)) %>%
  # Subjective but remove early (pre-february) and late (post Decemeber) dates
  dplyr::filter(JULIANDAY > 60) %>%  
  dplyr::filter(JULIANDAY < 330)

```



# Amount of data 
```{r}
hist(temp$year, breaks = 2023-1980)
length(unique(temp$DNRID))

total = temp %>% group_by(year, DNRID) %>% count()
mean(total$n)
```


# Run all GAMS
```{r}
# loops through columns 5-11 in the data frame temp and runs nb GAMMs
# TO DO - Play with offsets and counts 
models <- list()


for (i in 6:11) {
  
  single.model <- gam(temp[,i] ~ s(ice_off_anomaly) + s(JULIANDAY) + 
                      ti(ice_off_anomaly, JULIANDAY) +
                      s(DNRID, bs = "re") + s(year_f, bs = "re"),
                    method = "REML", select = T,
                    data = temp, family = tw(link = "log"))
  
  print(paste0("Finished ", colnames(temp)[i]))
  models[[paste0(colnames(temp)[i])]] <- single.model
}


summary(models$CYANOS)
summary(models$GREEN)
summary(models$DIATOM)
summary(models$DINOS)
summary(models$CRYPTOS)
summary(models$CHRYSOS)

appraise(models$CYANOS)
appraise(models$GREEN)
appraise(models$DIATOM)
appraise(models$DINOS)
appraise(models$CRYPTOS)
appraise(models$CHRYSOS)

k.check(models$CYANOS)
k.check(models$GREEN)
k.check(models$DIATOM)
k.check(models$DINOS)
k.check(models$CRYPTOS)
k.check(models$CHRYSOS)

write_rds(models, "./models/phyto.models.rds")
```

# Read in model DF
```{r}
models <- read_rds("./models/phyto.models.rds")
```



# Plot DOY change
## Figure S8
```{r}
hist(temp$JULIANDAY) # Approx 125-275 for peak sampling, look at 100 - 300
quantile(temp$JULIANDAY, c(0.05, 0.95))
hist(temp$ice_off_anomaly, breaks = 20)
quantile(temp$ice_off_anomaly)
# Thoughts to do - Change x-axis to Months

plot.phyto.doy = function(model = NA, var.name = NA, type = "plot", slice = 1, y.label = NA, 
                         early.anomaly = -17.52, late.anomaly = 14, 
                         start.date = 80, end.date = 274) {
  
  model <- models[[var.name]]
  # Year and DNRID aren't used but are required for predict.gam
  length <- length(seq(start.date, end.date, by = 1))
  pred.df <- data.frame(ice_off_anomaly = c(rep(early.anomaly, length), rep(0, length), 
                                            rep(late.anomaly, length)),
                        JULIANDAY = seq(start.date, end.date, by = 1), 
                        days_since_ice = seq(1, length),
                        TOW = 2,
                        DNRID = "62001200", year_f = "1981") 
  
  fit <- predict.gam(model, pred.df,
                     unconditional = T, # Gives simultaneous
                     type = "response",
                     exclude = c('s(DNRID)', 
                                's(year_f)'),
                     se.fit = T)
  pred.df$predictions = fit$fit
  pred.df$se = fit$se.fit
  
  y.label <- species.labels %>% filter(variable == var.name) %>% 
      dplyr::select(axis.label) %>% as.character()
  
  pred.df %>%
    mutate(ice_off_anomaly = as.factor(ice_off_anomaly),
           ice_off_descriptor = ifelse(ice_off_anomaly == early.anomaly, 
                                       "Early", "Normal"),
           ice_off_descriptor = ifelse(ice_off_anomaly == late.anomaly, 
                                       "Late", ice_off_descriptor),
           ice_off_descriptor = factor(ice_off_descriptor, 
                                       levels = c("Early", "Normal", "Late"))) %>%
    ggplot(aes(y = predictions, x = as.Date(JULIANDAY, origin = as.Date("2018-01-01")), 
               color = ice_off_anomaly)) +
    geom_line(aes(y = predictions, x = as.Date(JULIANDAY, origin = as.Date("2018-01-01")), 
                  color = ice_off_descriptor), lwd = 2) +
    theme_classic() +
    scale_x_date(date_breaks = "months" , date_labels = "%b") +
    scale_color_manual(values = c("#FF0000", "#000000", "#0000FF")) +
    labs(y = paste0(y.label), x = "Julian Day", 
         color = "Ice-Off \nAnomaly", fill = "Ice-Off \nAnomaly") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 16))
}
species.labels <- data.frame(variable = names(models), 
           axis.label = c("Cyanobacteria\nDensity", 
                          "Green-algae\nDensity", "Diatoms\nDensity", 
                          "Dinoflagellates\nDensity", "Cryptomonads\nDensity", 
                          "Chrysophytes\nDensity"))

cyanos.doy <- plot.phyto.doy(var.name = "CYANOS") + theme(legend.position="none")
green.doy <- plot.phyto.doy(var.name = "GREEN") + theme(legend.position="none")
diatom.doy <- plot.phyto.doy(var.name = "DIATOM") + theme(legend.position="none")
dinos.doy <- plot.phyto.doy(var.name = "DINOS") + theme(legend.position="none")
cryptos.doy <- plot.phyto.doy(var.name = "CRYPTOS") + theme(legend.position="none")
chrysos.doy <- plot.phyto.doy(var.name = "CHRYSOS")  + 
  theme(legend.position = c(0.75, 0.75))

phyto <- plot_grid(cyanos.doy, green.doy, diatom.doy,
                            dinos.doy, cryptos.doy, chrysos.doy)
phyto
#Figure S8
#ggsave("./figures/FigureS8.jpeg", height = 10, width = 12)
```

# Peak timing
## Figure S1
```{r}
toy.df <- data.frame(ice_off_anomaly = c(rep(early.anomaly, 201), rep(0, 201), 
                                          rep(late.anomaly, 201)),
                      JULIANDAY = seq(80, 280, by = 1), 
                      DNRID = "82016700", year_f = "2000") %>%
    mutate(ice_off_f =  ifelse(ice_off_anomaly == early.anomaly, "Early", "Normal"),
           ice_off_f =  ifelse(ice_off_anomaly == late.anomaly, "Late", ice_off_f),
           ice_off_f =  ifelse(ice_off_anomaly == 0, "Average", ice_off_f))


iters <- names(models)

timing.cis <- data.frame(group = character(0), 
                   numeric = numeric(0),
                   timing = character(0),
                   median = numeric(0),
                   lower.95 = numeric(0),
                   upper.95 = numeric(0),
                   lower.75 = numeric(0),
                   upper.75 = numeric(0))

pred.df = toy.df

for (i in 1:length(iters)) {
  model = models[[iters[i]]]
  
  if (iters[i] %in% c("GREEN", "DIATOM", "CRYPTOS", "CHRYSOS", "DINOS")) {
    pred.df = pred.df %>% filter(JULIANDAY < 182)
  }
  
  pred.df <- pred.df %>% mutate(row = row_number())
  
  # Use posterior dist of the mean to get posterior fitted values
  sims <- fitted_samples(model, exclude = c('s(DNRID)',  's(year_f)'),
                         data = pred.df, n = 1000, seed = 1024) |>
  left_join(pred.df |> select(row, ice_off_anomaly, JULIANDAY, ice_off_f), 
            by = join_by(row == row))
  
  
  # Get the peak timing when the ice off anomaly is big (ice-off happens late)
  early <- sims %>% filter(ice_off_anomaly == early.anomaly) %>% 
    group_by(draw) %>% slice_max(fitted)
  early.quant <- quantile(early$JULIANDAY, probs = c(.025,.975))
  early.quant.75 <- quantile(early$JULIANDAY, probs = c(.125, .875))
  early.median <- median(early$JULIANDAY)

  # Get the peak timing when the ice off anomaly is big (ice-off happens late)
  late <- sims %>% filter(ice_off_anomaly == late.anomaly) %>% 
    group_by(draw) %>% slice_max(fitted)
  late.quant <- quantile(late$JULIANDAY, probs = c(.025,.975))
  late.quant.75 <- quantile(late$JULIANDAY, probs = c(.125, .875))
  late.median <- median(late$JULIANDAY)
  
  average <- sims %>% filter(ice_off_anomaly == 0) %>% 
    group_by(draw) %>% slice_max(fitted)
  average.quant <- quantile(average$JULIANDAY, probs = c(.025,.975))
  average.quant.75 <- quantile(average$JULIANDAY, probs = c(.125, .875))
  average.median <- median(average$JULIANDAY)
  
  # Get the difference between peak timings
  diff.early <- early$JULIANDAY - average$JULIANDAY
  diff.earlymedian <- median(diff.early)
  diff.earlyquant <- quantile(diff.early, probs = c(.025,.975))
  diff.earlyquant.75 <- quantile(diff.early, probs = c(.125, .875))
  
  diff.late <- late$JULIANDAY - average$JULIANDAY
  diff.latemedian <- median(diff.late)
  diff.latequant <- quantile(diff.late, probs = c(.025,.975))
  diff.latequant.75 <- quantile(diff.late, probs = c(.125, .875))

  # Make new data frame to rbind to big data frame
  df <- data.frame(group = iters[[i]], 
                   numeric = i,
                   timing = c("Early", "Late", "Average", 
                              "Early Difference", "Late Difference"),
                   median = c(early.median, late.median, average.median, 
                              diff.earlymedian, diff.latemedian),
                   lower.95 = c(early.quant[1], late.quant[1], average.quant[1], 
                                diff.earlyquant[1], diff.latequant[1]),
                   upper.95 = c(early.quant[2], late.quant[2], average.quant[2],
                                diff.earlyquant[2], diff.latequant[2]),
                   lower.75 = c(early.quant.75[1], late.quant.75[1], average.quant.75[1],
                                diff.earlyquant.75[1], diff.latequant.75[1]),
                   upper.75 = c(early.quant.75[2], late.quant.75[2], average.quant.75[2],
                                diff.earlyquant.75[2], diff.latequant.75[2]))
  
  timing.cis <- rbind(timing.cis, df)
  pred.df = toy.df
}

row.names(timing.cis) <- NULL


species.labels <- data.frame(variable = names(models), 
  axis.label = c("Cyanobacteria", 
                          "Green-algae", "Diatom", 
                          "Dinoflagellate", "Cryptomonad", 
                          "Chrysophyte"))

timing.cis.plot <- timing.cis %>%
  mutate(jit = ifelse(timing == "Early", -0.15, 0.15),
         jit = ifelse(timing == "Average", 0, jit)) %>%
  merge(y = species.labels, by.x = "group", by.y = "variable") %>%
  mutate(axis.label = factor(axis.label, 
                             levels = c("Cyanobacteria", 
                          "Green-algae", "Diatom", 
                          "Dinoflagellate", "Cryptomonad", 
                          "Chrysophyte")))

timing.cis.plot$timing <- factor(timing.cis.plot$timing, 
                                 levels = c("Early", "Average", "Late", 
                                            "Early Difference", "Late Difference"))


timing.cis.plot %>%
  filter(!grepl("Difference", timing)) %>%
  ggplot() + 
  geom_point(aes(x = as.Date(median, origin = as.Date("2018-01-01")), y = -1*(numeric + jit), 
                 color = timing), size = 2) + 
  geom_segment(aes(y = -1*(numeric + jit), yend = -1*(numeric + jit), 
                   x = as.Date(lower.95, origin = as.Date("2018-01-01")), 
                   xend = as.Date(upper.95, origin = as.Date("2018-01-01")), color = timing)) +
  geom_segment(aes(y = -1*(numeric + jit), yend = -1*(numeric + jit), 
                   x = as.Date(lower.75, origin = as.Date("2018-01-01")), 
                   xend = as.Date(upper.75, origin = as.Date("2018-01-01")), 
                   color = timing), linewidth = 1.5) +
  #facet_grid(group ~., switch = "y") +
  theme_classic() +
  labs(y = "",
       x = "Day Peak Density Occurs", color = "Ice-off Anomaly") +
  theme(panel.grid.major.x = element_line(),
        panel.grid.minor.x = element_line(),
        strip.text.y.left = element_text(angle = 0, size = 12, face = 2),
        plot.title = element_text(angle = 0, size = 14, face = 2),
        strip.placement = "outside",
        strip.background = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.title.x = element_text(size = 16),
        legend.title = element_text(size = 14), 
        legend.text = element_text(size = 12)
        ) +
  scale_color_manual(values = c("#FF0000", "#000000", "#0000FF")) +
  scale_y_continuous(breaks = -1:-6, labels = levels(timing.cis.plot$axis.label)) +
  scale_x_date(date_labels = "%b")
  #scale_x_continuous(breaks = seq(100, 275, by = 25))
  
# Figure S1
ggsave("./figures/FigureS1.jpeg", height = 8, width = 8)

write.csv(timing.cis.plot, "./data/phyto_modeled_peak.csv", row.names = F)
```


# See if phytoplankton bloom size changes with ice-anomaly  
## Figure S7
```{r}
species.labels <- data.frame(variable = names(models), 
  axis.label = c("Cyanobacteria", "Green-Algae", 
                 "Diatom", "Dinoflagellate", "Cryptomonad", 
                 "Chrysophyte"))


bloom.size <- timing.cis.plot %>% 
  filter(!timing %in% c("Early Difference", "Late Difference")) %>% # filter out relative changes in timing
  mutate(row = row_number(), 
         ice_off_anomaly = ifelse(timing == "Early", early.anomaly, 0), 
         ice_off_anomaly = ifelse(timing == "Late",  late.anomaly, ice_off_anomaly))

bloom.size.plot <- data.frame(group = character(0), ice_off_anomaly = numeric(0),
                     median = numeric(0), 
                     q2.5 = numeric(0), q97.5 = numeric(0),
                     q25 = numeric(0), q75 = numeric(0))

groups = unique(bloom.size$group)

for (i in 1:length(groups)) {
  model = models[[groups[i]]]
  
  group.df <- bloom.size %>% filter(group == groups[i])
  
  pred.df <- data.frame(JULIANDAY = 
                          c(
                          seq(group.df$median[1] - 3, group.df$median[1] + 3, by = 1 ),
                          seq(group.df$median[2] - 3, group.df$median[2] + 3, by = 1 ),
                          seq(group.df$median[3] - 3, group.df$median[3] + 3, by = 1 )), 
                        ice_off_anomaly = c(rep(group.df$ice_off_anomaly[1], 7),
                                            rep(group.df$ice_off_anomaly[2], 7),
                                            rep(group.df$ice_off_anomaly[3], 7)),
                        DNRID = "82016700", year_f = "2000") %>% 
    mutate(row = row_number()) 
  
  sims <- fitted_samples(model, exclude = c('s(DNRID)',  's(year_f)'),
                         data = pred.df, n = 1000, seed = 1024) |>
    left_join(pred.df |> select(row, ice_off_anomaly, JULIANDAY), 
              by = join_by(row == row))
  
  
  early.diff <- ((sims[sims$ice_off_anomaly == early.anomaly,]$fitted - 
    sims[sims$ice_off_anomaly == 0,]$fitted) / 
    sims[sims$ice_off_anomaly == 0,]$fitted) * 100
  late.diff <- ((sims[sims$ice_off_anomaly == late.anomaly,]$fitted - 
    sims[sims$ice_off_anomaly == 0,]$fitted) / 
      sims[sims$ice_off_anomaly == 0,]$fitted) * 100
  
  temp_toadd <- data.frame(group = groups[i], 
                     ice_off_anomaly = c("Early", "Late"),
                     median = c(median(early.diff), median(late.diff)),
                     q2.5 = c(quantile(early.diff, prob = c(0.025)),
                              quantile(late.diff, prob = c(0.025))),
                     q97.5 = c(quantile(early.diff, prob = c(0.975)),
                              quantile(late.diff, prob = c(0.975))),
                     q25 = c(quantile(early.diff, prob = c(0.75)),
                              quantile(late.diff, prob = c(0.75))),
                     q75 = c(quantile(early.diff, prob = c(0.25)),
                              quantile(late.diff, prob = c(0.25))))
  bloom.size.plot <- rbind(bloom.size.plot, temp_toadd)
  
}

bloom.size.plot %>%
  merge(species.labels, by.y = "variable", by.x = "group") %>%
  ggplot() + 
  geom_point(aes(y = median, x = ice_off_anomaly, color = ice_off_anomaly)) + 
  geom_segment(aes(y = q2.5, yend = q97.5, x = ice_off_anomaly, 
                   xend = ice_off_anomaly, color = ice_off_anomaly)) + 
  geom_segment(aes(y = q25, yend = q75, x = ice_off_anomaly, 
                   xend = ice_off_anomaly, color = ice_off_anomaly), 
               linewidth = 1.5) +
  geom_hline(yintercept = 0, linetype = 'dotted') +
  facet_wrap(vars(axis.label), scales = "free") + 
  scale_color_manual(values = c("#FF0000",  "#0000FF")) + 
  labs(y = "% Change in Abundance From Normal Ice-Off",
       x = "Ice-Off Timing", color = "Ice-Off Timing") +
  theme_classic() +
  theme(legend.position = c(.45, .935)) 

# Figure S6
ggsave("./figures/FigureS6.jpeg", height = 8, width = 9)
```




# Graveyard - Not used in paper
# All in one model
```{r}
temp.long <- temp %>% 
  pivot_longer(cols = CYANOS:CHRYSOS, 
               names_to = "taxa", values_to = "values") %>%
  mutate(taxa = as.factor(taxa))


phyto_gam <- gam(values ~ 
                   te(JULIANDAY, ice_off_anomaly, m = 2, bs = "tp") + 
                   t2(JULIANDAY, ice_off_anomaly, taxa, m = 2, bs = c("tp", "tp", "re")) +
                   s(taxa, DNRID, bs = "re") + s(taxa, year_f, bs = "re"), 
                 method = "fREML", select = T,
                 data = temp.long, family = nb())
```

# Another way to do the same plot
## I dont think it zeroes out REs
```{r}
ds <- data_slice(models$CYANOS, var1 = "ice_off_anomaly")
fv <- fitted_values(models$CYANOS, data = ds)
  
fv |>
  ggplot(aes(x = ice_off_anomaly, y = fitted)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +
  geom_line() + 
  ylim(0, max(fv$upper))
```

# DOY change function - BAYESIAN
```{r}
plot.phyto.doy.bayes = function(model = NA, var.name = NA, type = "plot", slice = 1, y.label = NA, 
                         early.anomaly = -15, late.anomaly = 15, start.date = 90, end.date = 280) {
  if (is.na(model)) {
    model <- models[[var.name]]
  }
  # Year and DNRID aren't used but are required for predict.gam
  length <- length(seq(start.date, end.date, by = 1))
  pred.df <- data.frame(ice_off_anomaly_abs = 
                          c(rep(early.anomaly, length), rep(0, length), rep(late.anomaly, length)),
                        ice_off_anomaly = 
                          c(rep(early.anomaly, length), rep(0, length), rep(late.anomaly, length)),
                        JULIANDAY = seq(start.date, end.date, by = 1), 
                        days_since_ice = seq(1, length),
                        towdepth = 10,
                        DNRID = "62001200", year_f = "2000") %>%
    mutate(row = row_number()) %>% 
    mutate(
           ice_off_f =  ifelse(ice_off_anomaly == early.anomaly, "Early", "Normal"),
           ice_off_f =  ifelse(ice_off_anomaly == late.anomaly, "Late", ice_off_f))

  fv <- fitted_values(model, data = pred.df, exclude = c('s(DNRID)',  's(year_f)'))
  fs <- fitted_samples(model, data = pred.df, n = 20, seed = 1024,
                       exclude = c('s(DNRID)',  's(year_f)')) |>
    left_join(pred.df |> select(row, ice_off_anomaly, JULIANDAY), 
              by = join_by(row == row)) %>%
    drop_na()
  fit <- predict.gam(model, pred.df,
                     unconditional = T, # Gives simultaneous
                     type = "response",
                     exclude = c('s(DNRID)', 
                                's(year_f)'),
                     se.fit = T)
  pred.df$predictions = fit$fit
  pred.df$se = fit$se.fit
  
  if (type == "plot") {
    y.label <- species.labels %>% filter(variable == var.name) %>% 
        select(axis.label) %>% as.character()
    plot <- ggplot() +
      #geom_line(data = fs, 
      #          aes(group = draw, 
      #              x = as.Date(JULIANDAY, origin = as.Date("2018-01-01")),
      #              y = fitted, colour = ice_off_f), alpha = 0.4) +
      geom_line(data = pred.df, aes(y = predictions, 
                    x = as.Date(JULIANDAY, origin = as.Date("2018-01-01")), 
                    color = ice_off_f), lwd = 2) +
      geom_ribbon(data = fv, 
                  aes(x = as.Date(JULIANDAY, origin = as.Date("2018-01-01")),
                      y = fitted, ymin = lower, ymax = upper, 
                      fill = ice_off_f), alpha = 0.3) +
      theme_classic() +
      scale_x_date(date_breaks = "months" , date_labels = "%b") + 
      labs(y = paste0(y.label), x = "Julian Day", 
           color = "Ice-Off", fill = "Ice-Off") +
      theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 18),
        legend.title = element_text(size = 16), 
        legend.text = element_text(size = 16))
    
    return(plot)
  } # End plot if statement
  
  if (type == "max.date") {
    max.date <- pred.df %>% group_by(ice_off_anomaly) %>% slice_max(predictions, n = slice) %>% 
      mutate(zoop = var.name)
    max.date$predictions <- predict(model, newdata = max.date, 
                                    exclude = c("s(DNRID)", "s(year_f)"), 
                                    type = "response")
    max.date$se <- predict(model, newdata = max.date, exclude = c("s(DNRID)", "s(year_f)"), 
                           type = "response", se.fit = T)$se.fit
    
    return(max.date)
  } # End prediction if statement
}

```

# Plot DOY change - Bayesian
```{r}
species.labels <- data.frame(variable = names(models), 
           axis.label = c("All Cells\nDensity (No./mL)", "Cyanobacteria\nDensity", 
                          "Green-algae\nDensity", "Diatoms\nDensity", 
                          "Dinoflagellates\nDensity", "Cryptomonads\nDensity", 
                          "Chrysophytes\nDensity"))

all.cells.doy <- plot.phyto.doy.bayes(var.name = "ALL.CELLS") + theme(legend.position="none")
#all.cells.doy
cyanos.doy <- plot.phyto.doy.bayes(var.name = "CYANOS") + theme(legend.position="none")
green.doy <- plot.phyto.doy.bayes(var.name = "GREEN") + theme(legend.position="none")
diatom.doy <- plot.phyto.doy.bayes(var.name = "DIATOM") + theme(legend.position="none")
dinos.doy <- plot.phyto.doy.bayes(var.name = "DINOS") + theme(legend.position="none")
cryptos.doy <- plot.phyto.doy.bayes(var.name = "CRYPTOS") + theme(legend.position="none")
chrysos.doy <- plot.phyto.doy.bayes(var.name = "CHRYSOS") + theme(legend.position="none")

legend.example <- plot.phyto.doy.bayes(var.name = "CHRYSOS")
legend <- cowplot::get_legend(legend.example)
legend
phyto <- plot_grid(all.cells.doy, cyanos.doy, green.doy, diatom.doy,
                            dinos.doy, cryptos.doy, chrysos.doy, legend)

title <- ggdraw() + 
  draw_label(
    "Effects of Anomalous Ice-Off on Phytoplankton Concentrations Over the Year",
    fontface = 'bold', size = 23, x = 0, hjust = 0) +
  theme(
    plot.margin = margin(0, 0, 0, 7))

plot_grid(
  title, phyto,
  ncol = 1, rel_heights = c(0.1, 1)
)
#ggsave("./figures/all_phyto_doy.byaes.jpeg", height = 10, width = 12)
```
